# Generated by Django 2.2.4 on 2019-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='tfno',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
