# Generated by Django 2.2.4 on 2019-11-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_usuarios', '0004_auto_20191110_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='images/anonimo.png', null=True, upload_to='images/'),
        ),
    ]
