# Generated by Django 2.2.4 on 2019-11-16 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_usuarios', '0005_profile_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, default='Ninguno', max_length=254, null=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('logo', models.ImageField(blank=True, default='images/servicio.png', null=True, upload_to='logos/')),
                ('direccion', models.CharField(max_length=256)),
                ('longitud', models.FloatField(blank=True, default=None, null=True)),
                ('latitud', models.FloatField(blank=True, default=None, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestor_de_usuarios.Profile')),
            ],
        ),
    ]
