# Generated by Django 2.2.4 on 2019-11-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_usuarios', '0007_auto_20191117_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('Guardería', 'Guardería'), ('Niñera', 'Niñera'), ('Rescatista', 'Rescatista'), ('Refugio', 'Refugio'), ('Hogar de paso', 'Hogar de paso'), ('Centro de Adopción', 'Centro de Adopción'), ('Paseador', 'Paseador'), ('Servicio de Transporte', 'Servicio de Transporte'), ('Servicio Funerario', 'Servicio Funerario'), ('Fundación de ayuda', 'Fundación de ayuda')], default=None, max_length=100),
        ),
    ]
