# Generated by Django 2.2.4 on 2019-11-13 00:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_de_usuarios', '0004_auto_20191110_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=30)),
                ('tipo_lugar', models.CharField(choices=[('Clínicas veterinarias', 'Clínicas veterinarias'), ('Consultorios veterinarios', 'Consultorios veterinarios'), ('Refugios', 'Refugios'), ('Centros de adopción', 'Centros de adopción'), ('Fundaciones', 'Fundaciones'), ('Guarderías', 'Guarderias'), ('Sitio Pet Friendly', 'Sitio Pet Friendly'), ('Tiendas para mascotas', 'Tiendas para mascotas'), ('Spa para mascotas', 'Spa para mascotas'), ('Eventos', 'Eventos'), ('Zona dee peligro', 'Zona de peligro')], max_length=10)),
                ('telefono_cel', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=256)),
                ('direccion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Evento_global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=30)),
                ('tipo_evento', models.CharField(choices=[('Global', 'Global'), ('Personal', 'Personal')], max_length=10)),
                ('fecha_evento', models.DateField(verbose_name='Fecha del evento')),
                ('hora_evento', models.TimeField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_de_usuarios.Profile')),
            ],
        ),
    ]
