# Generated by Django 2.2.4 on 2019-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_global',
            name='hora_evento',
            field=models.DateTimeField(),
        ),
    ]
