# Generated by Django 2.2.4 on 2019-11-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_usuarios', '0004_auto_20191110_1123'),
        ('publicaciones', '0002_auto_20191113_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion_global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_de_usuarios.Topico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_de_usuarios.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Conversacion_global')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_de_usuarios.Profile')),
            ],
        ),
    ]
