# Generated by Django 2.2.4 on 2019-11-15 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_auto_20191113_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
