# Generated by Django 2.2.4 on 2019-11-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_auto_20191114_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='latitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='longitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
