# Generated by Django 2.2.4 on 2019-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_auto_20191115_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_global',
            name='fecha_evento',
        ),
        migrations.RemoveField(
            model_name='evento_global',
            name='hora_evento',
        ),
        migrations.AddField(
            model_name='evento_global',
            name='fecha_hora_evento_final',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='evento_global',
            name='fecha_hora_evento_inicio',
            field=models.DateTimeField(default=None),
        ),
    ]
