# Generated by Django 2.2.4 on 2019-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_auto_20191115_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='direccion',
            field=models.CharField(max_length=256),
        ),
    ]
