# Generated by Django 2.2.4 on 2019-11-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_auto_20191115_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='nombre_lugar',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo_lugar',
            field=models.CharField(choices=[('Clínicas veterinarias', 'Clínicas veterinarias'), ('Consultorios veterinarios', 'Consultorios veterinarios'), ('Refugios', 'Refugios'), ('Centros de adopción', 'Centros de adopción'), ('Fundaciones', 'Fundaciones'), ('Guarderías', 'Guarderias'), ('Sitio Pet Friendly', 'Sitio Pet Friendly'), ('Tiendas para mascotas', 'Tiendas para mascotas'), ('Spa para mascotas', 'Spa para mascotas'), ('Eventos', 'Eventos'), ('Zona dee peligro', 'Zona de peligro')], max_length=256),
        ),
    ]
