# Generated by Django 2.2.4 on 2019-11-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_auto_20191115_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_global',
            name='nombre_evento',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='evento_global',
            name='tipo_evento',
            field=models.CharField(choices=[('Global', 'Global'), ('Personal', 'Personal')], max_length=256),
        ),
    ]
