# Generated by Django 2.2.4 on 2019-11-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_evento_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_global',
            name='lugar',
        ),
    ]
