# Generated by Django 2.2.4 on 2019-11-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0013_remove_evento_global_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='longitud',
        ),
    ]
