# Generated by Django 2.2.4 on 2019-11-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0016_evento_global_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_global',
            name='direccion',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
