# Generated by Django 2.2.4 on 2019-11-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0017_auto_20191117_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_global',
            name='direccion',
        ),
    ]
