# Generated by Django 2.2.4 on 2019-11-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_de_usuarios', '0003_auto_20191101_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=6)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_de_usuarios.Profile')),
            ],
        ),
    ]
