# Generated by Django 2.2.4 on 2019-11-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0003_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('', '---------'), ('Pug', 'Pug')], default=None, max_length=30),
        ),
    ]
