# Generated by Django 2.2.4 on 2019-11-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0005_auto_20191108_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('Weimaraner', 'Weimaraner'), ('Viejo Pastor Inglés', 'Viejo Pastor Inglés'), ('Terrier Yorkshire', 'Terrier Yorkshire'), ('Terrier Escocés', 'Terrier Escocés'), ('Terranova', 'Terranova'), ('Springer Spaniel', 'Springer Spaniel'), ('Shih Tzu', 'Shih Tzu'), ('Shiba Inu', 'Shiba Inu'), ('Shar Pei', 'Shar Pei'), ('Schnauzer Miniatura', 'Schnauzer Miniatura'), ('San Bernardo', 'San Bernardo'), ('Rottweiler', 'Rottweiler'), ('Pug', 'Pug'), ('Poodle', 'Poodle'), ('Pomeranio', 'Pomeranio'), ('Pitbull terrier', 'Pitbull terrier'), ('Pinscher', 'Pinscher'), ('Corgi', 'Corgi'), ('Pekinés', 'Pekinés'), ('Pastor de Shetland', 'Pastor de Shetland'), ('Pastor Australiano', 'Pastor Australiano'), ('Pastor Alemán', 'Pastor Alemán'), ('Malamute de Alaska', 'Malamute de Alaska'), ('Labrador Retriever', 'Labrador Retriever'), ('Husky Siberiano', 'Husky Siberiano'), ('Gran Danés', 'Gran Danés'), ('Golden Retriever', 'Golden Retriever'), ('Galgo', 'Galgo'), ('Flat Coated Retriever', 'Flat Coated Retriever'), ('Doberman', 'Doberman'), ('Dálmata', 'Dálmata'), ('Dachshund', 'Dachshund'), ('Collie', 'Collie'), ('Cocker Spaniel', 'Cocker Spaniel'), ('Chow Chow', 'Chow Chow'), ('Chihuahua', 'Chihuahua'), ('Bulldog francés', 'Bulldog francés'), ('Bulldog', 'Bulldog'), ('Bóxer', 'Bóxer'), ('Boston Terrier', 'Boston Terrier'), ('Border Collie', 'Border Collie'), ('Basset Hound', 'Basset Hound'), ('Akita americano', 'Akita americano'), ('Criollo', 'Criollo')], default=None, max_length=30),
        ),
    ]
