# Generated by Django 2.2.4 on 2019-11-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0010_auto_20191113_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermedad',
            options={'ordering': ['nombre'], 'verbose_name': 'Enfermedad', 'verbose_name_plural': 'Enfermedades'},
        ),
        migrations.AlterModelOptions(
            name='enfermedad2',
            options={'ordering': ['nombre'], 'verbose_name': 'Enfermedad2', 'verbose_name_plural': 'Enfermedades2'},
        ),
    ]
