# Generated by Django 2.2.4 on 2019-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0011_auto_20191113_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='enfermedades_gato',
            field=models.ManyToManyField(blank=True, to='gestor_de_mascotas.Enfermedad2'),
        ),
    ]
