# Generated by Django 2.2.4 on 2019-11-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0012_mascota_enfermedades_gato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
