# Generated by Django 2.2.4 on 2019-11-13 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0015_auto_20191113_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tamanio',
            field=models.CharField(choices=[('', '---------'), ('Enano', 'Enano'), ('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande'), ('Gigante', 'Gigante')], default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
