# Generated by Django 2.2.4 on 2019-11-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0017_auto_20191115_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('', '---------'), ('Normal', 'Normal'), ('Perdido', 'Perdido'), ('Adopción', 'Adopcion'), ('Maltratado', 'Matratado'), ('Accidentado', 'Accidentado'), ('Encontrado', 'Encontrado')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.CharField(choices=[('', '---------'), ('Si', 'Si'), ('No', 'No')], max_length=3),
        ),
    ]
