# Generated by Django 2.2.4 on 2019-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_mascotas', '0020_auto_20191117_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, default='mascotas/anonima.jpg', null=True, upload_to='mascotas/'),
        ),
    ]
